// <auto-generated />
using System;
using MenteSaudavel.Server._02.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenteSaudavel.Server._02.Services.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estratificacao")
                        .HasColumnType("int");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<Guid>("RespondenteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RespondenteId");

                    b.ToTable("Questionario");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Resposta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionarioId");

                    b.ToTable("Resposta");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genero")
                        .HasColumnType("int");

                    b.Property<int>("IsAdmin")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.HasOne("MenteSaudavel.Server._03.Data.Entities.Usuario", "Respondente")
                        .WithMany("Questionarios")
                        .HasForeignKey("RespondenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respondente");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Resposta", b =>
                {
                    b.HasOne("MenteSaudavel.Server._03.Data.Entities.Questionario", "Questionario")
                        .WithMany("Respostas")
                        .HasForeignKey("QuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Questionario", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("MenteSaudavel.Server._03.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Questionarios");
                });
#pragma warning restore 612, 618
        }
    }
}
